export enum Role {
  ADMIN_GLOBAL = 'ADMIN_GLOBAL',
  PRESIDENCIA = 'PRESIDENCIA',
  TESOURARIA = 'TESOURARIA',
  CONSELHO_FISCAL = 'CONSELHO_FISCAL',
  CONTABILIDADE_UNICA = 'CONTABILIDADE_UNICA',
  SOCIO = 'SOCIO',
}

export const ROLE_HIERARCHY = {
  [Role.ADMIN_GLOBAL]: 10,
  [Role.PRESIDENCIA]: 9,
  [Role.TESOURARIA]: 8,
  [Role.CONSELHO_FISCAL]: 7,
  [Role.CONTABILIDADE_UNICA]: 6,
  [Role.SOCIO]: 1,
};